apiVersion: v1
name: frontend
description: Frontend of ts-example extension.
type: application
version: 0.0.1
appVersion: 0.0.1
home: https://kubesphere.io
sources:
  - https://github.com/kubesphere-extensions
